# Question
- How to cleave the data?

# install libarary

In [1]:
!pip install konlpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 19.4 MB 40.1 MB/s eta 0:00:01   |███▍                            | 2.1 MB 479 kB/s eta 0:00:37
     |████████████████████████████████| 453 kB 28.3 MB/s eta 0:00:01


In [2]:
# !/usr/bin/python3 -m pip install --upgrade pip

In [38]:
# !pip install mxnet
# !pip install gluonnlp pandas tqdm
# !pip install sentencepiece
# !pip install transformers
# !pip install torch

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [39]:
# !pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
  Cloning https://github.com/SKTBrain/KoBERT.git to /tmp/pip-install-wc2f0lq0/kobert-tokenizer_c8334ac4ce3741518a4c6a241b93439d
  Running command git clone --filter=blob:none --quiet https://github.com/SKTBrain/KoBERT.git /tmp/pip-install-wc2f0lq0/kobert-tokenizer_c8334ac4ce3741518a4c6a241b93439d
  Resolved https://github.com/SKTBrain/KoBERT.git to commit e1f2f37055e7460d8427f6912579c0162cb69831
  Preparing metadata (setup.py) ... done


In [4]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Wed Jun  1 22:00:00 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:D8:00.0 Off |                  N/A |
| 46%   64C    P2   314W / 350W |   6721MiB / 24576MiB |     74%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# data

source : https://github.com/naver/nlp-challenge/blob/master/missions/ner/data/train/train_data

In [140]:
import pandas as pd

In [141]:
# data = pd.read_csv('data/train_data.txt', sep='\t',  header=None)
# data.columns = ['index' , 'content', 'tag']
# data['word_id'] = [k for k in range(len(data['content']))]

In [142]:
# data = pd.read_csv('data/indexingFile.csv', sep=',',  header=0)
# data.columns = ['number', 'index' , 'content', 'tag']
# data = data.drop(['number'], axis=1)
# data['word_id'] = [k for k in range(len(data['content']))]

In [143]:
data = pd.read_csv('data/indexingFile_527.csv', sep=',',  header=0)
data.columns = ['number', 'index' , 'content', 'tag']
data = data.drop(['number'], axis=1)
data['word_id'] = [k for k in range(len(data['content']))]

In [144]:
data.head(25)

index content  tag  word_id
0       1      강사    1        0
1       2       로    0        1
2       3      활동    0        2
3       4      잘할    0        3
4       5      같은    0        4
5       1      일타    0        5
6       2      강사    1        6
7       3       로    0        7
8       4      같은    0        8
9       1      일타    0        9
10      2      강사    1       10
11      3      하면    0       11
12      4   스타는?.    0       12
13      1      일타    0       13
14      2      강사    1       14
15      3       로    0       15
16      4      하면    0       16
17      5       것    0       17
18      1      커피    1       18
19      1      커피    1       19
20      2      갤러    0       20
21      1      커피    1       21
22      2       리    0       22
23      1      커피    1       23
24      2       리    0       24

To split by a sentence

In [145]:
content_split = []
tag_split = []
word_id_split = []

content_spliter = []
tag_spliter = []
word_spliter = []

for i in range(len(data)):
    content_spliter.append(data['content'].iloc[i])
    tag_spliter.append(data['tag'].iloc[i])
    word_spliter.append(data['word_id'].iloc[i])
    if (i == len(data)-1) : # the last word in a data
        content_split.append(content_spliter)
        content_spliter = []
        tag_split.append(tag_spliter)
        tag_spliter = []
        word_id_split.append(word_spliter)
        word_spliter = []
    elif (data['index'].iloc[i+1] == 1) : # the last word in a sentence
        content_split.append(content_spliter)
        content_spliter = []
        tag_split.append(tag_spliter)
        tag_spliter = []
        word_id_split.append(word_spliter)
        word_spliter = []
        
# sanity check
len(content_split) == len(tag_split) == len(word_id_split)

True

In [146]:
len(content_split)

703464

In [147]:
len(tag_split)

703464

In [148]:
len(word_id_split)

703464

## vocabulary

konlpy tokenizer

In [149]:
from konlpy.tag import Okt
okt = Okt()

print('형태소 분석 :',okt.morphs("자연어 처리 연구를 기반으로 인공지능 모델을 구성하고 있습니다."))
print('품사 태깅 :',okt.pos("자연어 처리 연구를 기반으로 인공지능 모델을 구성하고 있습니다."))
print('명사 추출 :',okt.nouns("자연어 처리 연구를 기반으로 인공지능 모델을 구성하고 있습니다."))

형태소 분석 : ['자연어', '처리', '연구', '를', '기반', '으로', '인공', '지능', '모델', '을', '구성', '하고', '있습니다', '.']
품사 태깅 : [('자연어', 'Noun'), ('처리', 'Noun'), ('연구', 'Noun'), ('를', 'Josa'), ('기반', 'Noun'), ('으로', 'Josa'), ('인공', 'Noun'), ('지능', 'Noun'), ('모델', 'Noun'), ('을', 'Josa'), ('구성', 'Noun'), ('하고', 'Josa'), ('있습니다', 'Adjective'), ('.', 'Punctuation')]
명사 추출 : ['자연어', '처리', '연구', '기반', '인공', '지능', '모델', '구성']


To create the vocabulary corpus

In [180]:
# to select unique value in content_split
unique_content_list = list(set([x for sublist in content_split for x in sublist]))

# to select only string
filtered = filter(lambda voca: isinstance(voca, str), unique_content_list)
unique_filtered_content_list = list(filtered)

# concatenation for tokenizer
unique_filtered_content_str = ' '.join(unique_filtered_content_list)

# select nouns in order to reduce the number of tokens in the vocabulary corpus
tokenizer_voca = okt.nouns(unique_filtered_content_str)
tokenizer_voca = list(set(tokenizer_voca)) # to select the unique token
print(len(tokenizer_voca))
print(tokenizer_voca[:10])

21057


TypeError: 'set' object is not subscriptable

In [182]:
len(tokenizer_voca)

21057

In [184]:
tokenizer_voca[:10]

['락다운', '백지', '다이브', '언론사', '마렵구', '창작', '친척', '이빨', '다반', '카폐']

In [185]:
del voca2idex, idex2voca
voca2idex = {word: idx+5 for idx, word in enumerate(tokenizer_voca)}
voca2idex['<unk>']= 0 # unknown
voca2idex['<pad>']= 1 # padding
voca2idex['<bos>']= 2 # begining of sentence
voca2idex['<eos>']= 3 # end of sentence
voca2idex['<mask>']= 4 # masking

# configuration parameters
VOCA_SIZE = len(voca2idex)
print(VOCA_SIZE)

# index2voca
idex2voca = {v:k for k,v in voca2idex.items()}
#print(list(gene2idex.keys())[list(gene2idex.values()).index(16)]) 
print(len(idex2voca))
print(f'{idex2voca[0]}')

21062
21062
<unk>


voca to index

In [186]:
idex2voca[21061]

'스푼'

In [187]:
voca2idex['멋대로']

3361

In [188]:
# seq_to_index function
def sequence_to_index(string_list, voca2idex):
    '''
    INPUT
        string_list : string list
    OUTPUT
        integer list
    '''
    converted_index = [voca2idex[word] if word in voca2idex.keys() else voca2idex['<unk>'] for word in string_list]
    return converted_index

# example
print(sequence_to_index(['멋대로', '가나다라마'], voca2idex)) # example

[3361, 0]


## tag integer encodding

In [189]:
tag_list = data['tag'].unique()
num_tags = len(tag_list)
tag_list

array([1, 0])

In [190]:
# tag2idex = {tag: idx for idx, tag in enumerate(tag_list)}
# tag2idex

In [191]:
idex2tag = {}
idex2tag[0]='<unk>'
idex2tag[1]='<pad>'
idex2tag[2]='<bos>'
idex2tag[3]='<eos>'
idex2tag[4]='<mask>'
idex2tag[5]='non'
idex2tag[6]='coffe'

In [192]:
tag2idex = {'<unk>':0,'<pad>':1,'<bos>':2,'<eos>':3,'<mask>':4, 0:5, 1:6}

In [193]:
tag2idex[0]

5

In [194]:
# seq_to_index function
def tag_to_index(sequence, embedding_index):
    '''
    INPUT
        sequence : string list
    OUTPUT
        integer list
    '''
    converted_index = [embedding_index[word] if word in embedding_index.keys() else embedding_index['<unk>'] for word in sequence]
    return converted_index

# # index2gene
# idex2tag = {v:k for k,v in tag2idex.items()}
# idex2tag[0]='[UNK]'
# idex2tag[1]='[PAD]'
# idex2tag[2]='[CLS]'
# idex2tag[3]='[SEP]'
# idex2tag[4]='[MASK]'
# #print(list(gene2idex.keys())[list(gene2idex.values()).index(16)]) 
# print(f'{idex2tag[1]}')

print(tag_to_index(['5', '6'], tag2idex)) # example

[0, 0]


In [195]:
# tag_to_index(['PER_B', 'DAT_B'], tag2idex)

In [196]:
import pickle
with open("data/voca2idex.pickle", "wb") as fw:
    pickle.dump(voca2idex, fw)
with open("data/idex2voca.pickle", "wb") as fw:
    pickle.dump(idex2voca, fw)    
with open("data/tag2idex.pickle", "wb") as fw:
    pickle.dump(tag2idex, fw)
with open("data/idex2tag.pickle", "wb") as fw:
    pickle.dump(idex2tag, fw)

## tokenizer

In [ ]:
# content_tokenizer = []
# word_id_tokenizer = []
# tag_id_tokenizer = []
# label_ids_tokenizer = []
# for i in data['word_id'][0:50]:
#     # tokenizer
#     content_tokenizer += tokenizer.encode(data['content'].iloc[i])[1:-1]
#     word_id_tokenizer += [i]*(len(tokenizer.encode(data['content'].iloc[i]))-2)    
#     label_ids_tokenizer += [tag2idex[data['tag'].iloc[i]]] + [-100] * (len(tokenizer.encode(data['content'].iloc[i]))-3)
 
    
# data_tokenizer = pd.DataFrame({'token': content_tokenizer, 'word_id': word_id_tokenizer, 'label_ids': label_ids_tokenizer})

In [197]:
# tokenizer
tokenizer = okt.morphs

In [198]:
import numpy as np
import pandas as pd
def tokenizer_per_sentece(content_list, tag_list, word_id_list):
    """
    INPUT:
        content_split_list : a list that represents a sentence 
            e.g. ['비토리오', '양일', '만에', '영사관', '감호', '용퇴,', '항룡', '압력설', '의심만', '가율']
        tag_split_list
            e.g. ['PER_B', 'DAT_B', '-', 'ORG_B', 'CVL_B', '-', '-', '-', '-', '-']
        word_id_split_list
            e.g. [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    OUTPUT: tokenzier results
        content_tokenizer : a tokenized content list without special tokens
        word_id_tokenizer : a word id list
        tag_id_tokenizer : a tag id list that the only first content has a tag.
    """
    # sanity check
    if not (len(content_list)==len(tag_list)==len(word_id_list)):
        print("check the input data")
    
    # tokenizer
    content_tokenizer = []
    word_id_tokenizer = []
    tag_id_tokenizer = []
    
    # error handling : nan in input
    if any(pd.isna(content_list)):
        return [], [], []
    
    for i in range(len(word_id_list)):
        # tokenizer
        content_tokenizer += tokenizer(content_list[i]) # to remove special tokens [CLS] and [SEP]
        word_id_tokenizer += [word_id_list[i]] * (len(tokenizer(content_list[i])))
        tag_id_tokenizer += [tag2idex[tag_list[i]]] + [-100] * (len(tokenizer(content_list[i]))-1)
    
    # to convert string into index
    content_tokenizer = sequence_to_index(content_tokenizer, voca2idex)
    
    # error handling : tokenizer does not work properly
    if not (len(content_tokenizer) == len(word_id_tokenizer) == len(tag_id_tokenizer)):
        # tokenzier does not work properly becuase of noise.
        print(f'sanity check : {len(content_tokenizer) == len(word_id_tokenizer) == len(tag_id_tokenizer)}')
        content_tokenizer = []
        word_id_tokenizer = []
        tag_id_tokenizer = []
    return content_tokenizer, tag_id_tokenizer, word_id_tokenizer

In [199]:
content_split[0]

['강사', '로', '활동', '잘할', '같은']

In [200]:
a, b, c = tokenizer_per_sentece(content_split[0], tag_split[0], word_id_split[0])

In [201]:
a

[5227, 14215, 7432, 0, 9876, 0]

In [202]:
[idex2voca[word] for word in a]

['강사', '로', '활동', '<unk>', '할', '<unk>']

In [203]:
b

[6, 5, 5, 5, -100, 5]

In [204]:
c

[0, 1, 2, 3, 3, 4]

error case

In [205]:
content_split[172999]

['커피', '블렌드', '샀음', '500g', '아쉬움', '맛']

In [206]:
tag_split[172999]

[1, 1, 0, 1, 0, 1]

In [207]:
word_id_split[172999]

[509998, 509999, 510000, 510001, 510002, 510003]

In [208]:
a, b, c = tokenizer_per_sentece(content_split[172999], tag_split[172999], word_id_split[172999])

In [209]:
a

[893, 2421, 0, 0, 0, 17302, 20449]

Error case

In [210]:
content_split[500120]

[nan]

In [211]:
import numpy as np
np.isnan(content_split[500120])

array([ True])

In [212]:
np.isnan(content_split[500120])

array([ True])

In [213]:
type(content_split[500120][0])

float

In [214]:
a, b, c = tokenizer_per_sentece(content_split[500120], tag_split[500120], word_id_split[500120])

In [215]:
a

[]

error

In [216]:
content_split[598602]

['1', '1', 'coffee', nan, 'Mp']

In [217]:
pd.isna(content_split[598602])

array([False, False, False,  True, False])

In [218]:
any(pd.isna(content_split[598602]))

True

In [219]:
a, b, c = tokenizer_per_sentece(content_split[598602], tag_split[598602], word_id_split[598602])

In [220]:
from tqdm import tqdm 
def tokenizer_all_data(content_split, tag_split, word_id_split):
    # sanity check
    if not (len(content_split)==len(tag_split)==len(word_id_split)):
        print("check the input data")
        
    content_split_token, tag_split_token, word_id_split_token = [], [], []
    for i in tqdm(range(len((content_split)))):
        #print(i)
        content, tag, wordID = tokenizer_per_sentece(content_split[i], tag_split[i], word_id_split[i])
        content_split_token.append(content)
        tag_split_token.append(tag)
        word_id_split_token.append(wordID)
    return content_split_token, tag_split_token, word_id_split_token

In [221]:
content_split_tok, tag_split_tok, word_id_split_tok = tokenizer_all_data(content_split, tag_split, word_id_split)

100%|████████████████████████████████| 703464/703464 [1:11:04<00:00, 164.96it/s]


record
- 20220527 : KoBert
- 20220531 : Bert

In [222]:
import pickle
with open("data/content_split_tok_20220531.pickle", "wb") as fw:
    pickle.dump(content_split_tok, fw)
with open("data/tag_split_tok_20220531.pickle", "wb") as fw:
    pickle.dump(tag_split_tok, fw)
with open("data/word_id_split_tok_20220531.pickle", "wb") as fw:
    pickle.dump(word_id_split_tok, fw)

In [65]:
import torch
import pickle
with open("data/content_split_tok_20220531.pickle", "rb") as fr:
    content_split_tok = pickle.load(fr)
with open("data/tag_split_tok_20220531.pickle", "rb") as fr:
    tag_split_tok = pickle.load(fr)
with open("data/word_id_split_tok_20220531.pickle", "rb") as fr:
    word_id_split_tok = pickle.load(fr)

In [53]:
#example
[tokenizer.decode(token) for token in content_split_tok[0]]

['강', '사', '하면', '잘', '할', '스타', '는', '?', '.']

Padding

In [54]:
print(max([len(x) for x in content_split_tok]))
print(sum([len(x) for x in content_split_tok])/len(content_split_tok))

653
6.924360502429632


In [223]:
def prep_for_tensor(token_list, max_len=512):
    '''
    This function get a list of token lists and converts a input list into a list in size of max_len including special tokens.
    
    INPUT
        token_list : a list of token lists
            e.g. [[1,2,3,4], [5,6,7,8], [9, 10, 11, 12, 13, 14, 15]]
        max_len : int
    OUTPUT
        token_ls : a list of lists in size of max_len with special tokens. The last token that does not fit the size would be dropped.
            e.g. [[0, 1, 2, 3, 4, 0], [0, 5, 6, 7, 8, 0], [0, 9, 10, 11, 12, 0]]
    '''
    # setting
    max_len = max_len-2 # to consider the special tokens
    pad = 1 # an index of special token
    bos = 2 # an index of special token
    eos = 3 # an index of special token
    token_output_ls = []
    token_ls = []
    #token_ls_iter_position = 0 # index of the last element in token_ls
    
    for index, tokens in enumerate(token_list):
        n_token = len(tokens)
        
        if len(token_ls) + n_token <= max_len :
            token_ls += tokens
            #token_ls_iter_position += len(token_ls)
        else : 
            cut_position = max_len - len(token_ls)
            #assert cut_position >= 0
            token_ls += tokens[:cut_position]

            # to collect the current token_ls
            token_ls = [bos] + token_ls + [eos] # to add special tokens

            if not len(token_ls)-2 == max_len : 
                print(f'index: {index}')
                print(f'cut_position: {cut_position}')
                print(len(token_ls))
            assert len(token_ls)-2 == max_len
            token_output_ls.append(token_ls)

            # to update token_ls for next iteration
            token_ls = tokens[cut_position:]
            #token_ls_iter_position = len(token_ls) - 1
            
            # if token_ls is longer than max_len, it requires an additional cleavage
            while (len(token_ls) > max_len):
                token_output_ls.append([bos] + token_ls[:max_len] + [eos])
                token_ls = tokens[max_len:]
    return token_output_ls

In [224]:
content_input = prep_for_tensor(content_split_tok, 512)
tag_input = prep_for_tensor(tag_split_tok, 512)
word_id_input = prep_for_tensor(word_id_split_tok, 512)

In [132]:
content_split_tok[0]

[807, 6493, 517, 6079, 5141, 3942, 7836, 833]

In [58]:
content_split_tok[1]

[4656]

In [51]:
# def add_padding(token_list, max_len=512):
#     '''
#     INPUT
#         token_list : list
#             e.g. [[1,2,3,4], [5,6,7,8]]
#         max_len : int
#     OUTPUT
#         token_ls : list
#     '''
#     import copy
#     token_ls = copy.deepcopy(token_list)
#     max_len = max_len-2 # to consider the special tokens
#     for index, tokens in enumerate(token_ls):
#         n_token = len(tokens)
#         pad = 1 # an index of special token
#         bos = 2 # an index of special token
#         eos = 3 # an index of special token
#         # add padding if the length is shorter than max_len
#         if n_token < max_len:
#             token_ls[index] += [pad] * (max_len - n_token) # 부족한 만큼 padding을 추가함
        
#         # if a sentence is longer than max_len, cut a sentence.
#         elif n_token > max_len:
#             token_ls[index] = tokens[:max_len]
        
#         # to add begining token and end token
#         token_ls[index] = [bos] + token_ls[index] + [eos]
#     return token_ls

In [52]:
# content_input = add_padding(content_split_tok, 512)
# tag_input = add_padding(tag_split_tok, 512)
# word_id_input = add_padding(word_id_split_tok, 512)

In [53]:
# tag_input[100]

In [225]:
import pickle
with open("./data/content_input_20220531.pickle", "wb") as fw:
    pickle.dump(content_input, fw)
with open("./data/tag_input_20220531.pickle", "wb") as fw:
    pickle.dump(tag_input, fw)
with open("./data/word_id_input_20220531.pickle", "wb") as fw:
    pickle.dump(word_id_input, fw)

# To load data

In [27]:
import torch
import pickle

# to load dictionary corpus data
with open("./data/voca2idex.pickle", "rb") as fr:
    voca2idex = pickle.load(fr)
with open("./data/idex2voca.pickle", "rb") as fr:
    idex2voca = pickle.load(fr)
with open("./data/tag2idex.pickle", "rb") as fr:
    tag2idex = pickle.load(fr)
with open("./data/idex2tag.pickle", "rb") as fr:
    idex2tag = pickle.load(fr)

# to load train data  
with open("./data/content_input_20220531.pickle", "rb") as fr:
    content_input = pickle.load(fr)
with open("./data/tag_input_20220531.pickle", "rb") as fr:
    tag_input = pickle.load(fr)
with open("./data/word_id_input_20220531.pickle", "rb") as fr:
    word_id_input = pickle.load(fr)
    
# configuration parameters
VOCA_SIZE = len(voca2idex)
print(VOCA_SIZE)    

21062


# data loader

In [4]:
import torch

In [5]:
input_x = torch.tensor(content_input)
input_y = torch.tensor(tag_input)

In [6]:
input_x[0]

tensor([    2,  5227, 14215,  7432,     0,  9876,     0, 19157,   608,  5227,
        14215,     0, 19157,   608,  5227,     0,  2133,  3437,     0, 19157,
          608,  5227, 14215,     0, 18031,   893,   893,     0,   893, 19029,
          893, 19029,   893,   893,  3887,  6187,   893,   893,     0,   952,
            0,  9864,  9864,  9864,  9864,  5556, 11745, 11745, 20368,  5556,
        11745, 20368, 11745,    99,  4089,  8121, 20856, 18095,  4300,    99,
         4089,  8121, 19546, 20856, 18095,  4300,    99,  4089,  8121, 20856,
        18095,  4300,  5758,    99,  4089,  8121, 20856, 18095,  4300,  7182,
          893,  5287,     0,  7182,   893,  5287,  7182, 13088,   893,  5287,
         7182, 14129,   893,  5287,     0, 19314,     0,     0,  1685, 20670,
            0,     0,     0,  1685,     0,  4415,     0,     0,     0,  1685,
            0,  1685,  4415,  4415,   893,   893,   893,     0,   893,  1489,
         6664,     0, 15034,  6664, 10242,  1489,  6664, 15034, 

In [7]:
input_y[30]

tensor([   2,    5,    6,    6, -100,    6,    6, -100,    6,    6, -100,    6,
           5,    6, -100,    5, -100, -100, -100,    5,    6,    5,    6,    5,
           5,    6,    5,    5,    5, -100,    6,    5,    5,    5,    6,    6,
           5, -100,    6,    6,    5, -100,    6,    6,    5, -100,    6,    6,
           5, -100, -100,    5,    6,    5,    6,    5,    5,    6,    6,    5,
           6,    6,    6,    5,    6,    5,    5,    6,    6,    5,    5,    6,
           5,    5,    6,    6,    6,    5, -100, -100,    6,    6,    5,    5,
        -100, -100,    6,    6,    5,    5, -100, -100,    5,    6,    6,    5,
           5, -100, -100,    6,    6,    6,    6,    6,    5,    6,    6,    6,
           6,    6,    6,    6,    6,    5, -100,    6,    6,    6,    6,    5,
        -100,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
           5,    6,    5, -100,    5,    5, -100,    5,    6,    5, -100,    5,
           6,    5,    5,    5,    6,   

In [8]:
from torch.utils.data import TensorDataset 
from torch.utils.data import DataLoader
from torch.utils.data import random_split

batch_size=8
total_dataset = TensorDataset(input_x, input_y)

num_train = int(len(total_dataset)*0.8)
num_validation = int(len(total_dataset)*0.1)
num_test = len(total_dataset)-num_train-num_validation

train_dataset, validation_dataset, test_dataset = random_split(total_dataset, [num_train, num_validation, num_test])
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
validation_loader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=True, drop_last=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True, drop_last=True)


print(len(total_dataset))
print(len(train_dataset))
print(len(validation_dataset))
print(len(test_dataset))
print('sanity check: ', len(total_dataset)==len(train_dataset)+len(validation_dataset)+len(test_dataset))


len(train_loader)
len(validation_loader)
len(test_loader)

del total_dataset, num_train, num_validation, num_test, train_dataset, validation_dataset, test_dataset

6064
4851
606
607
sanity check:  True


# NER model

In [9]:
max_length = seq_length = 512
num_tag = 7

In [10]:
# predefined_args = {
#         'attention_cell': 'multi_head',
#         'num_layers': 12,
#         'units': 768, 
#         'hidden_size': 3072,
#         'max_length': 512,
#         'num_heads': 12,
#         'scaled': True,
#         'dropout': 0.1,
#         'use_residual': True,
#         'embed_size': 768,
#         'embed_dropout': 0.1,
#         'token_type_vocab_size': 2,
#         'word_embed': None,
#     }

In [11]:
from torch import Tensor
import torch
import torch.nn as nn
from torch.nn import TransformerEncoder
import math

# helper Module to convert tensor of input indices into corresponding tensor of token embeddings
class TokenEmbedding(nn.Module):
    def __init__(self, vocab_size: int, emb_size):
        super(TokenEmbedding, self).__init__()
        self.embedding = nn.Embedding(vocab_size, emb_size, padding_idx= int(voca2idex['<pad>']))
        self.emb_size = emb_size

    def forward(self, tokens: Tensor):
        return self.embedding(tokens.long()) * math.sqrt(self.emb_size)

    
class PositionalEncoding(nn.Module):
    def __init__(self,
                 emb_size: int,
                 dropout: float,
                 maxlen: int = max_length):
        super(PositionalEncoding, self).__init__()
        den = torch.exp(- torch.arange(0, emb_size, 2)* math.log(10000) / emb_size)
        pos = torch.arange(0, maxlen).reshape(maxlen, 1)
        pos_embedding = torch.zeros((maxlen, emb_size))
        pos_embedding[:, 0::2] = torch.sin(pos * den)
        pos_embedding[:, 1::2] = torch.cos(pos * den)
        pos_embedding = pos_embedding.unsqueeze(-2)

        self.dropout = nn.Dropout(dropout)
        self.register_buffer('pos_embedding', pos_embedding)

    def forward(self, token_embedding: Tensor):
        return self.dropout(token_embedding + self.pos_embedding[:token_embedding.size(0), :])



class BERT(nn.Module):
    def __init__(self,
                 num_encoder_layers: int,
                 emb_size: int,
                 nhead: int,
                 src_vocab_size: int,
                 dim_feedforward: int = 512,
                 num_labels=num_tag,
                 max_length=max_length,
                 dropout: float = 0.1):
        super(BERT, self).__init__()
        self.src_tok_emb = TokenEmbedding(vocab_size=src_vocab_size, emb_size=emb_size)
        self.positional_encoding = PositionalEncoding(emb_size, dropout=dropout)
        self.encoder_layer = nn.TransformerEncoderLayer(d_model=emb_size, nhead=nhead, dim_feedforward=dim_feedforward,
                                                       dropout=dropout, activation='gelu', batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(self.encoder_layer, num_layers=num_encoder_layers)
        self.classifier = nn.Linear(emb_size, num_labels)
        self.num_labels = num_labels
        self.max_length = max_length
        if dropout:
            self.dropout = nn.Dropout(p=dropout)

    def forward(self,
                src: Tensor,
                src_mask: Tensor,
                src_padding_mask: Tensor):
        # print(f'src.size(): {src.size()}')
        # print(f'src_tok_emb(src): {self.src_tok_emb(src)}')
        src_emb = self.positional_encoding(self.src_tok_emb(src))
        # print('transformer src: ', src)
        # print('transformer src_mask: ', src_mask)
        # print('transformer src_mask.size(): ', src_mask.size())
        # print('transformer src_padding_mask: ', src_padding_mask)
        # print('transformer src_padding_mask.size(): ', src_padding_mask.size()) 
        # print('transformer src_emb: ', src_emb)
        # print('transformer src_emb.size(): ', src_emb.size())
        output = self.transformer_encoder(src=src_emb, mask=src_mask, src_key_padding_mask=src_padding_mask) 
            # [batch_size, max_length, emb_size]
        # print('transformer_encoder output.size(): ', output.size())
        output = self.dropout(output)
        output = self.classifier(output) #[batch_size, max_length*num_label]
        # print('classifier output.size(): ', output.size())
        output = output.view([-1, self.num_labels, self.max_length]) # [batch_size, num_label, max_length]
        return output 

In [12]:
def generate_square_subsequent_mask(size):
    mask = (torch.triu(torch.ones((size, size), device=DEVICE)) == 1).transpose(0, 1)
    mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
    return mask

def create_mask(src):
    src_seq_len = src.shape[1] # src:  [batch_size, seq_length]
    src_padding_mask = (src == voca2idex['<pad>'])
    return src_padding_mask

In [13]:
# def generate_square_subsequent_mask(size):
#     mask = (torch.triu(torch.ones((size, size), device=DEVICE)) == 1).transpose(0, 1)
#     mask = mask.float().masked_fill(mask == 0, float('-inf')).masked_fill(mask == 1, float(0.0))
#     return mask

# def create_mask(src, tgt):
#     src_seq_len = src.shape[1] # src:  [batch_size, seq_length]
#     tgt_seq_len = tgt.shape[1] # tgt: [batch_size, seq_length]

#     tgt_mask = generate_square_subsequent_mask(tgt_seq_len)
#     src_mask = torch.zeros((src_seq_len, src_seq_len),device=DEVICE).type(torch.bool)

#     src_padding_mask = (src == voca2idex['<pad>'])
#     tgt_padding_mask = (tgt == voca2idex['<pad>'])
    
#     return src_mask, tgt_mask, src_padding_mask, tgt_padding_mask

In [17]:
SRC_VOCAB_SIZE = VOCA_SIZE #21062
EMB_SIZE = 512 # hidden # 512
NHEAD = 8 # 8
FFN_HID_DIM = 512  # 512
BATCH_SIZE = batch_size
NUM_ENCODER_LAYERS = 3

DEVICE = "cuda"
model = BERT(NUM_ENCODER_LAYERS, EMB_SIZE,
                                 NHEAD, SRC_VOCAB_SIZE, FFN_HID_DIM).to(DEVICE)

if torch.cuda.device_count() > 1:
    model = torch.nn.DataParallel(model)
    # dim = 0 [30, xxx] -> [10, ...], [10, ...], [10, ...] on 3 GPUs

In [18]:
loss_fn = torch.nn.CrossEntropyLoss()
for src, tgt in train_loader:
    src = src.type(torch.LongTensor).to(DEVICE)
    tgt = tgt.type(torch.LongTensor).to(DEVICE)
    src_padding_mask = create_mask(src)
    logits = model(src, None, src_padding_mask.to(DEVICE))
    print('logits: ')
    print(logits.size()) #[?, num_tags, seq_length]
    print(f'tgt: {tgt.size()}') #[batch_size, seq_length]
    loss = loss_fn(logits, tgt)
    print(loss)
    import gc
    gc.collect()
    torch.cuda.empty_cache()
    
    break

logits: 
torch.Size([8, 7, 512])
tgt: torch.Size([8, 512])
tensor(2.1009, device='cuda:0', grad_fn=<NllLoss2DBackward0>)


In [19]:
def train_epoch(model, optimizer, data_loader, max_length=max_length, DEVICE='cuda'):
    import gc
    from tqdm import tqdm
    model.train()
    loss_fn = torch.nn.CrossEntropyLoss()
    losses = 0
    num_correct = []
    num_test = 0
    torch.autograd.set_detect_anomaly(True)
    for src, tgt in data_loader:
        src = src.type(torch.LongTensor).to(DEVICE) #[batch_size, seq_length]
        tgt = tgt.type(torch.LongTensor).to(DEVICE) #[batch_size, seq_length]
        src_padding_mask = create_mask(src)
        logits = model(src, None, src_padding_mask)
            #torch.Size([batch_size, , num_tag, src_seq_length])
        optimizer.zero_grad()
        loss = loss_fn(logits, tgt)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 2)
        optimizer.step()
        losses += loss.item()
        
        # accuracy
        _, pred_word = torch.max(logits, dim=1)
        num_correct.append(int((torch.flatten(tgt)==torch.flatten(pred_word)).sum()))
        num_test += int(torch.flatten(pred_word).size(0))
        
    accuracy = sum(num_correct) / num_test
    
    # garbage collector
    gc.collect()
    torch.cuda.empty_cache()
 
    return losses / len(data_loader), accuracy


def test_epoch(model, optimizer, data_loader, max_length=max_length, DEVICE='cuda'):
    import gc
    import numpy as np
    with torch.no_grad():
        model.eval()
        loss_fn = torch.nn.CrossEntropyLoss()
        losses = 0
        num_correct = []
        num_test = 0
        y_probability = np.array([])
        y_pred = np.array([])
        y_true = np.array([])
        for src, tgt in data_loader:
            src = src.type(torch.LongTensor).to(DEVICE) #[batch_size, seq_length]
            tgt = tgt.type(torch.LongTensor).to(DEVICE) #[batch_size, seq_length]
            src_padding_mask = create_mask(src)
            logits = model(src, None, src_padding_mask)
                #torch.Size([batch_size, , num_tag, src_seq_length])
            
            loss = loss_fn(logits, tgt)
            losses += loss.item()
            
            # accuracy
            _, pred_word = torch.max(logits, dim=1)
            num_correct.append(int((torch.flatten(tgt)==torch.flatten(pred_word)).sum()))
            num_test += int(torch.flatten(pred_word).size(0))
            
            y_probability = np.append(y_probability, logits.cpu().detach().numpy())
            y_pred = np.append(y_pred, pred_word.cpu().detach().numpy())
            y_true = np.append(y_true, tgt.cpu().detach().numpy())
            
    accuracy = sum(num_correct) / num_test
    # garbage collector
    gc.collect()
    torch.cuda.empty_cache()
    
    return losses / len(data_loader), accuracy,  y_pred, y_true

In [20]:
def test_epoch_check(model, optimizer, data_loader, max_length=max_length, DEVICE='cuda'):
    import gc
    import numpy as np
    from tqdm import tqdm
    with torch.no_grad():
        model.eval()
        loss_fn = torch.nn.CrossEntropyLoss()
        losses = 0
        num_correct = []
        num_test = 0
        y_probability = np.array([])
        y_pred = np.array([])
        y_true = np.array([])
        for src, tgt in tqdm(data_loader):
            src = src.type(torch.LongTensor).to(DEVICE) #[batch_size, seq_length]
            tgt = tgt.type(torch.LongTensor).to(DEVICE) #[batch_size, seq_length]
            src_padding_mask = create_mask(src)
            logits = model(src, None, src_padding_mask)
                #torch.Size([batch_size, , num_tag, src_seq_length])
            
            loss = loss_fn(logits, tgt)
            losses += loss.item()
            
            # accuracy
            _, pred_word = torch.max(logits, dim=1)
            num_correct.append(int((torch.flatten(tgt)==torch.flatten(pred_word)).sum()))
            num_test += int(torch.flatten(pred_word).size(0))
            
            y_probability = np.append(y_probability, logits.cpu().detach().numpy())
            y_pred = np.append(y_pred, pred_word.cpu().detach().numpy())
            y_true = np.append(y_true, tgt.cpu().detach().numpy())
            
    accuracy = sum(num_correct) / num_test
    # garbage collector
    gc.collect()
    torch.cuda.empty_cache()
    
    return losses / len(data_loader), accuracy,  y_pred, y_true

In [23]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999), eps=1e-8)
train_epoch(model, optimizer=optimizer, data_loader=train_loader, max_length=max_length)
test_epoch_check(model, optimizer=optimizer, data_loader=validation_loader, max_length=max_length)

100%|██████████████████████████████████████████| 75/75 [00:00<00:00, 139.00it/s]


(1.9419976234436036,
 0.11638020833333333,
 array([3., 2., 1., ..., 6., 6., 3.]),
 array([   2.,    6.,    5., ...,    6., -100.,    3.]))

In [24]:
def slack_alarm(message):
    """
    message : string
    """
    import os
    from slack import WebClient
    from slack.errors import SlackApiError

    SLACK_API_TOKEN = 'xoxb-3456243383942-3465240022692-nQxw8PlFwhcywqhYlzO3jqmX'
    client = WebClient(token=SLACK_API_TOKEN)

    try:
        response = client.chat_postMessage(channel='#deep-learning',text=message)
        assert response["message"]["text"] == message

        #filepath="./tmp.txt"
        #response = client.files_upload(channels='#random', file=filepath)
        #assert response["file"]  # the uploaded file
    except SlackApiError as e:
        # You will get a SlackApiError if "ok" is False
        assert e.response["ok"] is False
        assert e.response["error"]  # str like 'invalid_auth', 'channel_not_found'
        print(f"Got an error: {e.response['error']}")

In [25]:
def train_all_sample(model, optimizer, max_length, train_loader, validation_loader, test_loader, device, total_num_epoch, running_num_epoch, tf_board_directory, model_save_directory, best_model_save_directory=None, slack_message=False):
    '''
    Parameters:
        train_loader
        validation_loader
        test_loader
        total_num_epoch : the total number of epoch that have run
        running_num_epoch : the number of epoch that run in this time
        tf_board_directory
        model_save_directory : save directory to save the final model
        best_model_save_directory : [optional] save directory to save the best model (best validation accuracy)
        slack_message : [boolian] slack message notification (current epoch)
    '''
    #################################################################################
    # load modules and set parameters
    from torch.utils.tensorboard import SummaryWriter
    writer = SummaryWriter(tf_board_directory)
        ## logdir=./python/run/GAT_Net/run_02

    if (total_num_epoch < 0 or running_num_epoch <= 0):
        import sys
        sys.exit("Check the number of epoch. It is incorrect")

    # optimizer = torch.optim.Adam(model.parameters(), lr=3e-6, weight_decay=0.95)
    # scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min',factor=0.7, patience=50, min_lr=1e-8)

    #################################################################################
    #running code
    import time
    from tqdm import tqdm
    import numpy as np
    total_time_start = time.time() # to measure time
    best_validation_accuracy = None
    for epoch in tqdm(range(1, running_num_epoch+1)):
        epoch_time_start = time.time() # to measure time
        lr = scheduler.optimizer.param_groups[0]['lr']
        loss, train_accuracy = train_epoch(model, optimizer, train_loader, max_length=max_length)
        _, validation_accuracy, _, _ = test_epoch(model, optimizer, validation_loader, max_length=max_length)
        #scheduler.step(validation_accuracy)

        # to save the metrics and model
        if best_validation_accuracy is None or validation_accuracy >= best_validation_accuracy:
            best_validation_accuracy = validation_accuracy
            if not(best_model_save_directory is None):            
                torch.save({
                'epoch': total_num_epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'loss': loss,
                }, best_model_save_directory)
        _, test_accuracy, _, _ = test_epoch(model, optimizer, test_loader, max_length=max_length)
        total_num_epoch = total_num_epoch + 1
        epoch_time_end = time.time() # to measure time    
        writer.add_scalar('loss in train', loss, total_num_epoch) #tensorboard
        writer.add_scalar('train accuracy', train_accuracy, total_num_epoch) #tensorboard
        writer.add_scalar('validation accuracy', validation_accuracy, total_num_epoch) #tensorboard    
        writer.add_scalar('test accuracy', test_accuracy, total_num_epoch) #tensorboard
        writer.add_scalar('learning rate', lr, total_num_epoch) #tensorboard
        # print(f'ToTal Epoch: {total_num_epoch:03d}, LR: {lr:7f}, Loss: {loss:.7f}, '
        #       f'Val MAE: {validation_error:.7f}, Test MAE: {test_error:.7f}, Time: {epoch_time_end - epoch_time_start}')

        # to send message
        if slack_message:
            slack_alarm('[Life3 server JupyterNotebook] : ' + str(epoch) + ' / ' + str(running_num_epoch) + '\ntrain accuracy: ' + str(train_accuracy) + '\nvalidation_accuracy: ' + str(validation_accuracy) + '\ntest_accuracy: ' + str(test_accuracy))
            
    total_time_finish = time.time() # to measure time
    print(f'Done. Total running Time: {total_time_finish - total_time_start}')
    writer.close() #tensorboard : if close() is not declared, the writer does not save any valeus.

    # model save
    torch.save({
            'epoch': total_num_epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': loss,
            }, model_save_directory)
    print('total number of epoches : ', total_num_epoch)
    print("-------------------------done------------------------------")

In [26]:
save_directory = 'run_03'
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-4)
#optimizer = torch.optim.RMSprop(model.parameters(), lr=0.0015334791245047435)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min',factor=0.8, patience=10, min_lr=1e-4)

train_all_sample(model=model,
                optimizer=optimizer,
                max_length=max_length,
                train_loader=train_loader, 
                validation_loader=validation_loader, 
                test_loader=test_loader, 
                device='cuda', 
                total_num_epoch=0, 
                running_num_epoch=2, 
                tf_board_directory = 'tfboard/'+save_directory, 
                model_save_directory='model/'+save_directory, 
                best_model_save_directory='model/'+save_directory+'_best',
                slack_message = True)
del save_directory
slack_alarm('The program execution on JupyterNotebook is done')

100%|█████████████████████████████████████████████| 2/2 [01:49<00:00, 54.84s/it]


Done. Total running Time: 109.69192624092102
total number of epoches :  2
-------------------------done------------------------------


# To load model

In [86]:
import torch
from transformers import BertModel
pretrained_model = BertModel.from_pretrained('skt/kobert-base-v1')

In [87]:
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim

class KoBERTNER(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768, #768
                 num_labels=29,
                 max_length=512, 
                 dr_rate=None,
                 params=None):
        super(KoBERTNER, self).__init__()
        self.bert = bert # Load model body
        self.dr_rate = dr_rate
        self.max_length = max_length
        # Set up token classification head
        self.num_labels = num_labels # num_tags
        self.classifier = nn.Linear(hidden_size, self.max_length*self.num_labels)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)
            
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, input_ids, attention_mask):
        output = self.bert(input_ids=input_ids, attention_mask=attention_mask) #[batch_size, hidden_dim]
            # ouitput[0] : the attention weights
            # output[1] : the output from the model
        # Apply classifier to encoder representation
        output = self.dropout(output[1])
        output = self.classifier(output) #[batch_size, max_length*num_label]
        output = output.view([-1, self.num_labels, self.max_length]) # [batch_size, num_label, max_length]
        return output
#     def forward(self, token_ids, valid_length, segment_ids):
#         attention_mask = self.gen_attention_mask(token_ids, valid_length)

#         # Use model body to get encoder representations
#         _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
#         # Apply classifier to encoder representation
#         sequence_output = self.dropout(pooler)
#         logits = self.classifier(sequence_output)
#         return logits

In [90]:
DEVICE = "cuda"
model = KoBERTNER(pretrained_model, dr_rate=0.3).to(DEVICE)
optimizer = torch.optim.RMSprop(model.parameters(), lr=0.0015334791245047435)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min',factor=0.8, patience=5, min_lr=0.00001)
#optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
PATH = 'model/run_01_best'

checkpoint = torch.load(PATH)
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

In [ ]:
def output_visualization(model, optimizer, data_loader, max_length=max_length, DEVICE='cuda'):
    import gc
    import numpy as np
    with torch.no_grad():
        model.eval()
        loss_fn = torch.nn.CrossEntropyLoss()
        losses = 0
        num_correct = []
        num_test = 0
        y_probability = np.array([])
        y_pred = np.array([])
        y_true = np.array([])
        for src, tgt in data_loader:
            src = src.type(torch.LongTensor).to(DEVICE)
            tgt = tgt.type(torch.LongTensor).to(DEVICE)
            logits = model(input_ids= src, attention_mask= torch.tensor([[1]*max_length]*batch_size).to(DEVICE))
                #torch.Size([batch_size, , num_tag, src_seq_length])
            
            loss = loss_fn(logits, tgt)
            losses += loss.item()
            
            # accuracy
            _, pred_word = torch.max(logits, dim=1)
            num_correct.append(int((torch.flatten(tgt)==torch.flatten(pred_word)).sum()))
            num_test += int(torch.flatten(pred_word).size(0))
            
            y_probability = np.append(y_probability, logits.cpu().detach().numpy())
            y_pred = np.append(y_pred, pred_word.cpu().detach().numpy())
            y_true = np.append(y_true, tgt.cpu().detach().numpy())
            
    accuracy = sum(num_correct) / num_test
    # garbage collector
    gc.collect()
    torch.cuda.empty_cache()
    
    return losses / len(data_loader), accuracy,  y_pred, y_true

In [93]:
loss, accuracy, pred, true = test_epoch(model=model, optimizer=optimizer, data_loader= test_loader, max_length=max_length, DEVICE='cuda')

In [94]:
loss

0.7274990410640322

In [ ]:
[1 2 3 4] [true f t f ] -> [1 3]

In [101]:
from itertools import compress
list_a = [1, 2, 4, 6]
fil = [True, False, True, False]
list(compress(list_a, fil))

[1, 4]

In [104]:
from itertools import compress
true_vis = list(compress(true, [(x==5 or x==6) for x in true]))
pred_vis = list(compress(pred, [(x==5 or x==6) for x in true]))

In [108]:
ner_result = pd.DataFrame({'prediction' : pred_vis, 'label' : true_vis})
ner_result

prediction  label
0             5.0    5.0
1             5.0    5.0
2             6.0    6.0
3             5.0    5.0
4             6.0    5.0
...           ...    ...
55970         5.0    5.0
55971         5.0    6.0
55972         5.0    6.0
55973         6.0    5.0
55974         5.0    5.0

[55975 rows x 2 columns]

In [113]:
result = [x==y for (x,y) in zip(true_vis, pred_vis)]
acc = sum(result)/len(result)

In [ ]:
acc

0.5042072353729343

In [95]:
pred[2000:3000]

array([5., 5., 5., 6., 5., 5., 5., 6., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       6., 6., 5., 6., 6., 5., 5., 6., 6., 6., 5., 6., 5., 5., 6., 6., 5.,
       5., 5., 5., 5., 6., 5., 5., 5., 6., 5., 6., 5., 5., 3., 2., 5., 5.,
       5., 6., 5., 5., 6., 5., 6., 6., 6., 6., 5., 5., 6., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 6., 6., 5., 5., 5., 5., 5., 6., 5., 6., 6., 5.,
       6., 5., 6., 5., 5., 6., 6., 5., 6., 6., 5., 5., 6., 5., 5., 6., 5.,
       6., 6., 5., 5., 5., 5., 6., 5., 6., 5., 5., 5., 6., 5., 5., 6., 6.,
       5., 5., 6., 5., 5., 6., 5., 6., 6., 5., 6., 6., 6., 6., 5., 6., 5.,
       5., 6., 5., 6., 5., 5., 6., 5., 6., 5., 5., 5., 5., 5., 5., 5., 5.,
       6., 6., 5., 5., 6., 6., 5., 5., 5., 6., 5., 6., 5., 5., 5., 5., 6.,
       5., 6., 5., 5., 6., 5., 5., 6., 5., 5., 5., 5., 5., 6., 5., 5., 5.,
       6., 6., 6., 5., 5., 6., 5., 5., 5., 5., 5., 5., 5., 6., 5., 6., 6.,
       6., 5., 5., 5., 5., 5., 5., 6., 6., 6., 5., 6., 5., 5., 6., 5., 5.,
       5., 6., 5., 5., 5.

In [96]:
true[1000:2000]

array([-100., -100.,    6., -100., -100.,    6., -100., -100.,    6.,
          6., -100.,    6., -100.,    5., -100.,    6., -100., -100.,
       -100.,    6., -100.,    6., -100.,    3.,    2.,    5., -100.,
          6.,    5., -100., -100.,    5., -100.,    6., -100.,    5.,
       -100., -100., -100., -100.,    5., -100.,    6.,    5., -100.,
       -100.,    5., -100., -100., -100.,    5., -100.,    6.,    6.,
          5., -100., -100.,    6., -100.,    5., -100., -100.,    5.,
          6., -100., -100.,    5., -100.,    5.,    6., -100.,    6.,
       -100.,    6., -100.,    5., -100.,    5., -100.,    5., -100.,
       -100., -100., -100., -100.,    5.,    5.,    5.,    6.,    5.,
       -100.,    5., -100.,    6., -100.,    5.,    6., -100.,    5.,
       -100.,    5.,    5.,    5.,    5., -100., -100., -100., -100.,
          5., -100.,    6.,    6., -100., -100.,    5., -100.,    6.,
       -100.,    6., -100., -100.,    5.,    6.,    5., -100.,    6.,
          5.,    6.,

# Model example

In [ ]:
from kobert_tokenizer import KoBERTTokenizer
tokenizer = KoBERTTokenizer.from_pretrained('skt/kobert-base-v1')
tokenizer.encode("한국어 모델을 공유합니다.")

BPE-dropout을 이용하면 서비스에 적합한 띄어쓰기에 강건한 모델로 튜닝 할 수 있습니다. 학습시 아래와 유사한 토크나이저 설정으로 학습을 진행할 수 있습니다. 자세한 옵션 설명은 이곳을 참고하세요  
https://github.com/SKTBrain/KoBERT/tree/master/kobert_hf

In [ ]:
from kobert_tokenizer import KoBERTTokenizer
import gluonnlp as nlp
vocab = nlp.vocab.BERTVocab.from_sentencepiece(tokenizer.vocab_file, padding_token='[PAD]')

In [385]:
vocab

Vocab(size=8002, unk="[UNK]", reserved="['[CLS]', '[SEP]', '[MASK]', '[PAD]']")

In [ ]:
import torch
from transformers import BertModel
pretrained_model = BertModel.from_pretrained('skt/kobert-base-v1')
text = "한국어 모델을 공유합니다."
inputs = tokenizer.batch_encode_plus([text])
out = pretrained_model(input_ids = torch.tensor(inputs['input_ids']),
              attention_mask = torch.tensor(inputs['attention_mask']))
out.pooler_output.shape

In [386]:
inputs['input_ids']

[[2, 4958, 6855, 2046, 7088, 1050, 7843, 54, 3]]

In [387]:
inputs['attention_mask']

[[1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [388]:
out

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.1554, -0.0150,  0.3673,  ..., -0.0094,  0.1067,  0.0844],
         [ 0.1229, -0.3236, -0.0669,  ..., -0.4487, -0.1753, -0.2302],
         [ 0.1008, -0.3885, -0.1219,  ..., -0.2129, -0.0330, -0.1708],
         ...,
         [-0.0700,  0.1174, -0.1385,  ..., -0.0272,  0.5141, -0.0093],
         [-0.0605, -0.2776,  0.4285,  ..., -0.2879,  0.5493,  0.0797],
         [-0.1537, -0.1819, -0.1994,  ..., -0.2862,  0.0133,  0.0783]]],
       grad_fn=<NativeLayerNormBackward>), pooler_output=tensor([[-1.5197e-02,  1.2525e-02, -2.0906e-02, -4.9571e-02, -9.7731e-01,
          9.9156e-01, -6.7530e-01,  5.5347e-02,  2.3231e-02,  4.5099e-03,
         -5.1811e-01, -3.6802e-02, -4.0091e-02, -7.1836e-02, -2.3317e-02,
          8.3534e-01, -9.9642e-01,  5.2746e-02,  2.5372e-03, -8.5501e-02,
          1.1586e-01, -4.6591e-02, -2.1023e-02,  5.6610e-01,  3.4027e-02,
          7.5981e-01, -9.3067e-01, -6.7136e-02, -9.6185e-01, -1.7121

In [384]:
out[0].size()

torch.Size([1, 9, 768])

In [383]:
out[1].size()

torch.Size([1, 768])